--- 
abstract: wrap up programs to be run as cron jobs
author: 
  - Ricardo Signes <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: App-Cronjob
requires: 
  Digest::MD5: 0
  Email::Sender::Transport::Sendmail: 0
  Email::Simple: 0
  Email::Simple::Creator: 0
  Errno: 0
  Fcntl: 0
  Getopt::Long::Descriptive: 0
  IPC::Run3: 0
  Log::Dispatchouli: 0
  String::Flogger: 0
  Sys::Hostname::Long: 0
  Text::Template: 0
  Time::HiRes: 0
version: 1.000
